#!/bin/sh

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}"
CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}"

THEME_DIR="${BOOTIQUE_THEME_DIR:-$CONFIG_DIR/bootique/themes}"
TEMPLATE_DIR="${BOOTIQUE_TEMPLATE_DIR:-$CONFIG_DIR/bootique/templates}"
OUTPUT_DIR="${BOOTIQUE_OUTPUT_DIR:-$CACHE_DIR/bootique/theme}"
DMENU_COMMAND="${BOOTIQUE_DMENU_COMMAND:-dmenu -i -p Theme}"

die() {
    >&2 printf "[\033[0;31mERROR\033[0m] %s\n" "$*"
    exit 1
}

# Remove comments, empty lines, and unnecesary whitespace
to_parsable() {
	sed -e 's/!.*$//' -e '/^[[:space:]]*$/d' \
	-e 's/:[[:space:]]*/:/' -e 's/^[[:space:]]*//' "$@"
}

parse_template() {
	theme="$1"
	template="$2"
	template_contents=$(cat "$template")

	while read -r line; do
		key=${line%%:*}
		value=${line#*:}

		template_contents=$(echo "$template_contents" | sed "s@<$key>@$value@g")
	done << THEME
		$(to_parsable "$theme")
THEME

	while read -r line; do
		[ "$line" ] || continue # weird bug where I'm given a few extra lines
		line="${line#*<}"
		line="${line%>*}"
		command="${line%%:*}"
		args="${line#*:}"
		command -v "$command" > /dev/null && {
			value=$(eval "$command" "$args")
			template_contents=$(echo "$template_contents" | sed "s@<$line>@$value@")
		} || die "'$command' does not exist!"

	done << MODS
		$(echo "$template_contents" | grep "<[^>]*:[^>]*>")
MODS

	echo "$template_contents"
}

changetheme() {
	filefromtemplate() {
		filename="${2##*/}"
		filename="${filename%.*}"
		outputfile=$(parse_template "$1" "$2")
		outputpath="$OUTPUT_DIR/$filename"

		[ "$outputfile" ] && {
			[ -d "$OUTPUT_DIR" ] || mkdir -p "$OUTPUT_DIR"

			fileexec=$(echo "$outputfile" | grep "[[:space:]]*booexec" \
			| sed 's@<file>@'"$outputpath"'@g')

			outputfile=$(echo "$outputfile" | sed '/^booexec/d')
			echo "$outputfile" > "$outputpath"

			echo "$fileexec" | while read -r line; do
				eval "${line#*:}"
			done
		}
	}

	[ -f "$1" ] || die "$1 is not a file"

	theme="$1"
	template_target="${2:-$TEMPLATE_DIR}"

	[ -e "$template_target" ] && {
		find "$template_target" -name "*.template" | \
		while read -r template; do
			filefromtemplate "$theme" "$template"
		done
	} || die "Invalid template target"
}

menu() {
	COMMAND_BASE="${DMENU_COMMAND%% *}"

	command -v "$COMMAND_BASE" > /dev/null || \
	die "dmenu command '$COMMAND_BASE' not installed"

	cd "$THEME_DIR" || exit 1

	theme=$(find . -name '*.theme' | sed 's:\./::g' | $DMENU_COMMAND)
	changetheme "$theme" "$1"

	exit
}

help() {
>&2 cat << "EOF"
Options:
    -h, --help
    	display this help page

    -t, --theme <theme path>
    	target theme file used to parse templates (not used with --menu)

    -p, --template <template path>
    	target template file or directory that the theme will be applied to, if not set then $BOOTIQUE_TEMPLATE_DIR will be used

    -m, --menu
    	select the theme from a list using $BOOTIQUE_DMENU_COMMAND populated with files from $BOOTIQUE_THEME_DIR

Evironment variables:
    BOOTIQUE_THEME_DIR
    	directory where themes are stored, used for the --menu option
        DEFAULT = $XDG_CONFIG_HOME/bootique/themes

    BOOTIQUE_TEMPLATE_DIR
    	directory where templates are stored, used when no template file or directory is provided
        DEFAULT = $XDG_CONFIG_HOME/bootique/templates

    BOOTIQUE_OUTPUT_DIR
    	directory where theme files are output
        DEFAULT = $XDG_CACHE_HOME/bootique/theme

    BOOTIQUE_DMENU_COMMAND
    	command used for the --menu option, can be any command that accepts newline-delimited piped input such as dmenu, rofi, fzf, etc.
        DEFAULT = dmenu -i -p Theme
EOF
	exit
}

[ "$1" ] || help

# Parse options
while [ "$1" ]; do
	case $1 in
		-h|--help)
			help
			break
			;;
		-m|--menu)
			menu=true
			;;
		-t|--theme)
			[ "$theme" ] && die "Cannot set more than one theme"
			theme="$(echo "$2" | tr -d \')"
			shift
			;;
		-p|--template)
			[ "$template" ] && die "Cannot set more than one template, set a directory instead"
			template="$(echo "$2" | tr -d \')"
			shift
			;;
		*)
			die "Invalid arg '$1'"
			;;
	esac
	shift
done

: "${template:=$TEMPLATE_DIR}"

# Refactor to case statement?
[ "$menu" ] && menu "$template"
[ "$theme" ] && changetheme "$theme" "$template"
